
name: php_init
version: 0.0.1
language: php
description: PHP environment initialize
public: true
tags:
  - php
  - init
inputs:
  - name: FLOW_VERSION
    editable: false
outputs:
script_path: ./run.sh  
  
template: |  
  
  